[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#f97316"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#18181b"
textColor = "#fafafa"
font = "sans serif"

[browser]
gatherUsageStats = false

